# Команда для перезагрузки: /eclimiter
# Права:
# enderchestlimiter.reload - Разрешает перезагружать плагин
# enderchestlimiter.bypass.all - Даёт обход для любых лимитов
# enderchestlimiter.bypass.<название группы> - Даёт обход лимита выбранной группы
#
# Плейсхолдеры внутри плагина:
# %max% - выводит лимит на предмет
#
# Предметы (Оставьте groups: пустым, чтобы отключить)
groups:
  # Название группы (Может быть любым, но оно потребуется для пермишена на байпасс)
  shulker_boxes: # enderchestlimiter.bypass.shulker_boxes - чтобы обходить лимит
    # Максимально количество предметов из списка которые игрок сможет положить в эндер сундук
    limit: 3
    # Сообщение, которое будет отправляться если лимит: 1, 21, 31, 41, 51 итд
    deny-message-1: '&cИзвините, но вы не можете положить в ваш эндер сундук больше чем %max% шалкер'
    # Сообщение, которое будет отправляться если лимит: 2, 3, 22, 23, 32 итд
    deny-message-2: '&cИзвините, но вы не можете положить в ваш эндер сундук больше чем %max% шалкера'
    # Сообщение, которое будет отправляться если лимит: 4, 5, 11, 16, 26 итд
    deny-message-3: '&cИзвините, но вы не можете положить в ваш эндер сундук больше чем %max% шалкеров'
    # Звук, который будет воспроизводиться (Если удалить, то не будет)
    # Может быть в формате:
    # ITEM_SHIELD_BREAK или ITEM_SHIELD_BREAK;громкость или ITEM_SHIELD_BREAK;громкость;высота
    deny-sound: ITEM_SHIELD_BREAK;0.8;1
    # Группированные предметы на которые будет распространяться лимит
    included-items:
      - BLACK_SHULKER_BOX
      - BLUE_SHULKER_BOX
      - BROWN_SHULKER_BOX
      - CYAN_SHULKER_BOX
      - GRAY_SHULKER_BOX
      - GREEN_SHULKER_BOX
      - LIGHT_BLUE_SHULKER_BOX
      - LIGHT_GRAY_SHULKER_BOX
      - LIME_SHULKER_BOX
      - MAGENTA_SHULKER_BOX
      - ORANGE_SHULKER_BOX
      - PINK_SHULKER_BOX
      - PURPLE_SHULKER_BOX
      - RED_SHULKER_BOX
      - WHITE_SHULKER_BOX
      - YELLOW_SHULKER_BOX
  # Пример
  tnt:
    limit: 64 # 1 стак
    deny-message-1: '&cИзвините, но вы не можете положить в ваш эндер сундук больше чем %max% тнт'
    deny-message-2: '&cИзвините, но вы не можете положить в ваш эндер сундук больше чем %max% тнт'
    deny-message-3: '&cИзвините, но вы не можете положить в ваш эндер сундук больше чем %max% тнт'
    included-items:
      - TNT

# Сообщения
messages:
  # Сообщение при перезагрузке плагина
  reload-message: '&aПлагин EnderChestLimiter успешно перезагружен.'
  # Сообщения если не хватает прав на использование команды
  no-permission: '&cИзвини, но у тебя не хватает прав на использование данной команды.'