# Команда для перезагрузки: /eclimiter
# Права:
# enderchestlimiter.reload - Разрешает перезагружать плагин
# enderchestlimiter.bypass.all - Даёт обход для любых лимитов
# enderchestlimiter.bypass.<название группы> - Даёт обход лимита выбранной группы
#
# Плейсхолдеры внутри плагина:
# %max% - выводит лимит на предмет
#
settings:
  config-version: 1.0
  use-minimessage: false

# Предметы (Оставьте groups: пустым, чтобы отключить)
groups:
  # Название группы (Может быть любым, но оно потребуется для пермишена на байпасс)
  # enderchestlimiter.bypass.shulker_boxes - чтобы обойти этот лимит
  shulker_boxes:
    # Максимально количество предметов из списка которые игрок сможет положить в эндер сундук
    limit: 3
    # Сообщение, которое будет отправляться если лимит превышен
    deny-message: '&cИзвините, но вы не можете положить в ваш эндер сундук больше чем 3 шалкера.'
    # Звук, который будет воспроизводиться (Если удалить, то не будет)
    # Указывать как НАЗВАНИЕ_ЗВУКА;ГРОМКОСТЬ;ВЫСОТА (громкость и высота необязательны)
    deny-sound: ITEM_SHIELD_BREAK;0.8;1
    # Предметы на которые будет распространиться лимит данной группы
    included-items:
      - BLACK_SHULKER_BOX
      - BLUE_SHULKER_BOX
      - BROWN_SHULKER_BOX
      - CYAN_SHULKER_BOX
      - GRAY_SHULKER_BOX
      - GREEN_SHULKER_BOX
      - LIGHT_BLUE_SHULKER_BOX
      - LIGHT_GRAY_SHULKER_BOX
      - LIME_SHULKER_BOX
      - MAGENTA_SHULKER_BOX
      - ORANGE_SHULKER_BOX
      - PINK_SHULKER_BOX
      - PURPLE_SHULKER_BOX
      - RED_SHULKER_BOX
      - WHITE_SHULKER_BOX
      - YELLOW_SHULKER_BOX
  # Пример
  tnt:
    limit: 128 # 2 стака
    deny-message: '&cИзвините, но вы не можете положить в ваш эндер сундук больше чем 128 тнт.'
    included-items:
      - TNT

# Сообщения
messages:
  # Сообщение при перезагрузке плагина
  reload: '&2(!) &aПлагин EnderChestLimiter успешно перезагружен за %time%мс.'
  # Сообщения если не хватает прав на использование команды
  no-perm: '&4(!) &cИзвините, но у Вас не хватает прав на использование данной команды!'